version: 2

env:
  - GO111MODULE=on
  - CGO_ENABLED=0
builds:
  - id: go
    flags:
      - -trimpath
      - -tags=netgo
    goos:
      - darwin
      - linux
      #- windows
    goarch:
      - amd64
      #- arm64
    binary: wtutf-{{ .Os }}-{{ .Arch }}
    mod_timestamp: "{{ .CommitTimestamp }}"
    buildmode: "c-archive"
    ldflags:
      - "-s -w"
      - "-X main.date={{ .CommitDate }}"
      - "-X main.Version={{ .Version }}"
      - "-X main.Commit={{ .FullCommit }}"
      - "-X main.CommitDate={{ .CommitDate }}"
dockers:
  - image_templates:
      - "ghcr.io/eliheady/{{ .ProjectName }}:{{ .Tag }}-{{ .Arch }}"
    dockerfile: Containerfile
    build_flag_templates:
      - --platform {{ .Os }}/{{ .Arch }}
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/eliheady/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/eliheady/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .CommitDate }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
docker_manifests:
  - name_template: ghcr.io/eliheady/{{ .ProjectName }}:{{ .Tag }}
    image_templates:
      - ghcr.io/eliheady/{{ .ProjectName }}:{{ .Tag }}-{{ .Arch }}