name: Sign Artifact

on:
  workflow_call:
    inputs:
    
      subject-path:
        required: false
        type: string
        default: 'release'

      push-to-registry:
        required: false
        type: boolean

      show-summary:
        required: false
        type: boolean
    outputs:
      attestation-url:
        value: ${{ jobs.sign-artifact.outputs.attestation-url }}

      attestation-id:
        value: ${{ jobs.sign-artifact.outputs.attestation-id }}

      bundle-path:
        value: ${{ jobs.sign-artifact.outputs.bundle-path }}

jobs:
  sign-artifact:
    name: Sign Artifacts

    outputs:
      attestation-url: ${{ steps.collect.outputs.attestation-url }}
      attestation-id: ${{ steps.collect.outputs.attestation-id }}
      bundle-path: ${{ steps.collect.outputs.bundle-path }}

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      attestations: write
      contents: read

    steps:
    # Download the artifacts uploaded by the build job
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: ${{ inputs.subject-path }}

    - name: Attest Build Provenance
      id: attest
      uses: actions/attest-build-provenance@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        subject-path: ${{ inputs.subject-path }}/*
        push-to-registry: ${{ inputs.push-to-registry }}
        show-summary: ${{ inputs.show-summary }}

    - name: Set outputs
      id: collect
      run: |
        echo "attestation-url=${{ steps.attest.outputs.attestation-url }}" >> $GITHUB_OUTPUT
        echo "attestation-id=${{ steps.attest.outputs.attestation-id }}" >> $GITHUB_OUTPUT
        echo "bundle-path=${{ steps.attest.outputs.bundle-path }}" >> $GITHUB_OUTPUT
