name: "RELEASE: Make Draft Release"

on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+-slsa-*

permissions: read-all

jobs:
  draft_release:
    name: draft release
    runs-on: ubuntu-latest
    outputs:
      attestation-url: ${{ steps.attest.outputs.attestation-url }}
      image-digest: ${{ steps.metadata.outputs.image-digest }}
      image-name: ${{ steps.metadata.outputs.image-name }}
      artifacts: ${{ steps.metadata.outputs.artifacts }}
      metadata: ${{ steps.metadata.outputs.metadata }}

    permissions:
      attestations: write
      contents: write
      id-token: write
      packages: write
      pull-requests: write

    steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ^1.23

    - name: Goreleaser release
      id: release
      uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: release --clean --draft
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate Attestation
      id: attest
      uses: actions/attest-build-provenance@v2
      with:
        subject-path: |
          dist/**/*wtutf*tar.gz
          dist/**/*wtutf*checksums.txt

    - name: metadata
      id: metadata
      env:
        ARTIFACTS: ${{ steps.release.outputs.artifacts }}
        METADATA:  ${{ steps.release.outputs.metadata }}
      run: |
        echo "artifacts=$(echo "$ARTIFACTS" )" >> "$GITHUB_OUTPUT"
        echo "metadata=$(echo "$METADATA" )" >> "$GITHUB_OUTPUT"
        echo "image-digest=$(echo "$ARTIFACTS" | jq -r '.[]|select(.type=="Docker Manifest")|select(.name|test(":v"))|.extra.Digest')" >> "$GITHUB_OUTPUT"
        echo "image-name=$(echo "$ARTIFACTS" | jq -r '.[]|select(.type=="Docker Manifest")|select(.name|test(":v"))|.name|split(":")[0]')" >> "$GITHUB_OUTPUT"

    #- name: Generate container attestation
    #  uses: actions/attest-build-provenance@v2
    #  with:
    #    subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    #    # todo: figure out where goreleaser stores the image sha
    #    subject-digest: ${{ fromJson(steps.release.outputs.metadata).somekey }}
    #    push-to-registry: true

  output:
    runs-on: ubuntu-latest
    needs: draft_release
    steps:
    - name: debug
      env:
        ATTESTATION_URL: ${{ needs.draft-release.outputs.attestation-url }}
        IMAGE_DIGEST: ${{ needs.draft-release.outputs.image-digest }}
        IMAGE_NAME: ${{ needs.draft-release.outputs.image-name }}
        ARTIFACTS: ${{ needs.draft-release.outputs.artifacts }}
        METADATA: ${{ needs.draft-release.outputs.metadata }}
      run: |
        echo "attestation:"
        echo "$ATTESATION_URL"
        echo "image:"
        echo "$IMAGE_DIGEST"
        echo "$IMAGE_NAME"
        echo "artifacts:"
        echo "$ARTIFACTS"
        echo "metadata:"
        echo "$METADATA"

  #notes:
  #  runs-on: ubuntu-latest
  #  needs: draft-release
  #  permissions:
  #    contents: write
  #  steps:
  #  - name: Append Release Notes
  #    id: notes
  #    uses: goreleaser/goreleaser-action@v6
  #    with:
  #      version: latest
  #      args: release --config .goreleaser-notes.yml --skip archive
  #    env:
  #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

