name: "RELEASE: Make Draft Release"
  

on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+-slsa-*

permissions: read-all

jobs:
  draft_release:
    outputs:
      hashes: ${{ steps.collect.outputs.hashes }}
    name: draft release
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      pull-requests: write
    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ^1.23
    -
      id: release
      name: Goreleaser release
      uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Collect artifact digests
      id: collect
      run: |
        echo "hashes=$(find dist -type f -name \*wtutf\* -exec sha256sum {} \; | base64 -w0)" >> "$GITHUB_OUTPUT"

  provenance:
    needs: [draft_release]
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
    with:
      base64-subjects: "${{ needs.draft_release.outputs.hashes }}"
      upload-assets: true
      draft-release: true
