name: |
  RELEASE: Make Draft Release

on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+-slsa-*

jobs:
  draft_release:
    outputs:
      base64-subjects: ${{ steps.collect.outputs.base64-subjects }}
    name: draft release
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      pull-requests: write
    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ^1.23
    #-
    #  id: release
    #  name: Goreleaser release
    #  uses: goreleaser/goreleaser-action@v6
    #  with:
    #    distribution: goreleaser
    #    version: latest
    #    args: release
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    -
      id: build
      name: Goreleaser build
      uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: build
        binary: "{{ .ProjectName }}_{{ .Tag }}"
        name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Collect artifact metadata
      id: collect
      run: |
        ls -R dist
        # Generate sha256sum-style output for each artifact
        subjects=""
        for file in $(find dist -type f -name "wtutf*"); do
          echo "Processing artifact \"$file\""
          sha256=$(sha256sum "$file" | awk '{print $1}')
          subjects+="$sha256 $file\n"
        done

        # Base64 encode the subjects
        echo "base64-subjects=$(echo -e "$subjects" | base64 -w0)" >> "$GITHUB_OUTPUT"

  provenance:
    needs: [draft_release]
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
    with:
      base64-subjects: "${{ needs.draft_release.outputs.base64-subjects }}"
      upload-assets: true
      draft-release: true
